### ISSUE TITLE
targets-minimal repo doesn't exist

### ISSUE THREAD

**Issue by jarodmeng** [ropensci-books/targets#28]
## Prework

* [ ] I understand and agree to this repository's [code of conduct](https://ropensci.org/code-of-conduct/).
* [ ] I understand and agree to this repository's [contributing guidelines](https://github.com/ropensci-boooks/targets-manual/blob/main/CONTRIBUTING.md).
* [ ] I am reasonably sure this is a genuine bug in this repository's code and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)

## Description

[Chapter 2](https://github.com/ropensci-books/targets/blob/main/walkthrough.Rmd#L59) mentions a targets-minimal repo that contains the source code and data for the walkthrough example, but the link fails.

**Comment by jarodmeng** [comment]
The right link seems to be https://github.com/wlandau/targets-minimal. Not sure if it's supposed to be eventually transferred to ropensci.

**Comment by wlandau** [comment]
Thanks, the manual is now refreshing with the current link. Should be rebuilt in a few minutes.
