### ISSUE TITLE
Small typos in drake chapter

### ISSUE THREAD

**Issue by rCarto** [ropensci-books/targets#30]
https://github.com/ropensci-books/targets/blob/e88de5e91778b515ba3c6358bf4ea55d4992da85/drake.Rmd#L5

Suggested changes in bold here:

[`targets`](https://github.com/ropensci/targets) is the successor of [`drake`](https://github.com/ropensci/drake), an older pipeline tool. [`drake`](https://github.com/ropensci/drake) is [superseded](https://lifecycle.r-lib.org/articles/stages.html#superseded), which means there are no plans for new features or discretionary enhancements, but basic maintenance and support **~~and~~** will continue indefinitely. Existing projects that use [`drake`](https://github.com/ropensci/drake) can safely continue to use [`drake`](https://github.com/ropensci/drake), and there is no need to retrofit [`targets`](https://github.com/ropensci/targets). New projects should use [`targets`](https://github.com/ropensci/targets) because it **is** friendlier and more robust.

**Comment by wlandau** [comment]
Thanks for catching those. Please feel free to submit pull requests for other typos you find.

**Comment by rCarto** [comment]
Yes sure, I thought it would be easier for you via issues for such a small change.
