### ISSUE TITLE
Add more mentions of tarchetypes custom invalidation rules?

### ISSUE THREAD

**Issue by maelle** [ropensci-books/targets#36]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://ropensci.org/code-of-conduct/).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/ropensci-boooks/targets-manual/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I am getting started with targets (such a cool package / ecosystem of packages!) and started wondering how to create a target with a cue that'd be different from the ones in targets, then I discovered https://docs.ropensci.org/tarchetypes/reference/index.html#section-targets-with-custom-invalidation-rules which is exactly what I need. Should these functions be mentioned from

* https://docs.ropensci.org/targets/reference/tar_cue.html
* and/or somewhere in this book?

**Comment by wlandau** [comment]
Sure, maybe [here](https://github.com/ropensci-books/targets/blob/e7edbb16c7600ac4a729c0517757406c176aedf2/walkthrough.Rmd#L181) and [here](https://github.com/ropensci/targets/blob/main/R/tar_cue.R#L23)?

**Comment by wlandau** [comment]
I think I addressed your request in https://github.com/ropensci/targets/commit/171522b283fb3c274afca51e4d220c8ef5311095 and https://github.com/ropensci-books/targets/commit/9992d38dd2bb898b1edb88b610368d67a6a41b3b. Please let me know if there is anything I missed.

**Comment by maelle** [comment]
Yes, awesome, thank you!!
