### ISSUE TITLE
Load packages in consistent manner in document

### ISSUE THREAD

**Issue by atusy** [ropensci-books/targets#42]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci-books/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci-books/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

The section "Target script file" from Ch. 2 suggests loading packages other than targets via `tar_option_set` instead of `library`.

> https://books.ropensci.org/targets/walkthrough.html#target-script-file

However, the section "Workspace" from Ch. 4 is using `library(tidyverse)` in `_targets.R`.

> https://books.ropensci.org/targets/debugging.html#workspaces

I'd suggest the change below.

> https://github.com/atusy/targets/commit/04512f522ab3dbe72c5b8bf931e222aede13084d

Please describe the issue.

To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

**Comment by atusy** [comment]
and maybe `library(tibble)` in

> https://books.ropensci.org/targets/static.html#dynamic-within-static-branching

But I am not sure if there is any drawback from using `library`.

**Comment by wlandau** [comment]
Sounds reasonable. Should rebuild and post soon.

**Comment by atusy** [comment]
Great. Thank you.
