### ISSUE TITLE
Maintainer out of office: September 13-20, 2021

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/targets#53]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci-books/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I will be on vacation from September 13 through 20, and I will not have internet access most of the time. If you have experience with `targets`, it would be great if you would help answer new questions posted to [issues](https://github.com/ropensci-books/targets/issues) and [discussions](https://github.com/ropensci-books/targets/discussions). There are few new posts in a typical week. Thanks in advance.

**Comment by ginolhac** [comment]
Enjoy the well deserved vacation 😊

**Comment by wlandau** [comment]
Thanks, Aurélien!
