### ISSUE TITLE
Incorrect link to functions chapter?

### ISSUE THREAD

**Issue by samleenz** [ropensci-books/targets#70]
https://github.com/ropensci-books/targets/blob/4ea7035d7c087e609ffb76928757777181c59c95/walkthrough.qmd#L87C61-L87C151

Hi,

I was just having a read through of this documentation. It seems to me like perhaps this link should point to https://books.ropensci.org/targets/functions.html and not https://books.ropensci.org/targets/debugging.html#functions

Please ignore if I'm mistaken about this!

Thanks 😊

**Comment by wlandau** [comment]
Thanks, should be fixed now.
