### ISSUE TITLE
Clarify documentation about `findGlobals()` edge cases in a central place, and add comment on S3 methods

### ISSUE THREAD

**Issue by alexpghayes** [ropensci-books/targets#73]
I propose adding a new "Edge cases that fail" subsection to the walkthrough chapter (or elsewhere), and collating all code dependencies failure cases there.

This could include:

1. Namespaced function calls `pkg::func()` breaking things
2. The fact that `targets` does not correctly invalidate targets generated by S3 methods when those methods get updated.

For the second, consider

```r
library(targets)

my_generic <- function(x) {
  UseMethod("my_generic")
}

my_generic.default <- function(x) {
  sum(x^3)
}

list(
  tar_target(
    vec,
    rnorm(100)
  ),
  tar_target(
    result,
    my_generic(vec)
  )
)
```

Run `tar_make()`, change `my_generic.default()` to anything you want, and note that running `tar_make()` again does not re-run the `result` target.

**Comment by wlandau** [comment]
I understand the motivation for this, and I understand that some edge cases come up very frequently for some users. However, looking that this issue generally, there are too many code analysis failure modes to count. Even if this were its own chapter, the manual would get very long. I prefer the manual to be compact and digestible so users can go thought it and feel like they know enough to get started. As you area aware, GitHub issues and discussions are searchable and allow space to properly dive into these rabbit holes.
